version: '3'

services:
  nginx:
    build: ./nginx
    image: philmarshalldev/test-digital-ocean:nginx
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: ./web
    image: philmarshalldev/test-digital-ocean:web
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"